### PR TITLE
Update the latest code

### PR DESCRIPTION
**Pull request by ziyuhehe**
## Type of Changes

- [x] New content for the documentation
- [ ] Modification in the existing documentation
- [ ] Infrastructure changes (not related to documentation content)

## Checklist

- [x] My changes are rendered as expected by running `yarn start`.
- [x] My changes follow the [style guide](https://github.com/MicroStrategy/rest-api-docs/blob/public/contributing/content-style-guide.md).
- [x] I have self-reviewed this PR.

### CODE REVIEW

**Review by Aran0011 — APPROVED** [review]
LGTM

**Comment by Aran0011** [comment]
@ziyuhehe The lint check fails

**Comment by ziyuhehe** [comment]
> @ziyuhehe The lint check fails

fixed.

**Comment by ziyuhehe** [comment]
close as the CI scans blocked.

**Pull request closed without merging**
